language: cpp

env:
  global:
    - BUILD_TYPE=Debug
    - CMAKE_BUILD_PARALLEL_LEVEL=4
    - GTEST_COLOR=1

# SonarQube needs an unshallow clone for some of its
# functions to work properly.
git:
  depth: false

notifications:
  slack:
    secure: vaAkYdaPoqEfT7kHkGHqcobdFUeP2CIgOOjHD0bjkRQhk4qR9P+FN31BmyduFclPzWUHW98t+XwAkM6Pfv/NYjLeZAhvNHJHiR+kgYGgOq1hTTKdlhkQdyRnNQY7RuyPqmGHJI2SFHvGZJ6OCN2nKe+JK84BQ3/26eyTG81nq2Xgc9pKBMAeMXVTrS2+d0mDNyQukC8aATlclu5PnBsx8clL8yqAscC1gD5odnaXh9IVe0A4SgnUS1g3vrCbPqrU1pLI1DC55Ug2YNzE7GSx1Tqh+zMTwQJ+G+4Qdn5QFwp95hiJNkpid8wwRgeWtFJsKKJb6oFEhZymxhuPwAZMX1ktu5cQO5N7ggUr5YbvgbOTozc0KLKtUxGSAc/4TPlruZIvRfwdMwj2EoXd82X0XJAd/dJEsHCzwFm+UR5MkbZ3GH1QS6oMb/C10yQEDnkPhn5rga1zyNPxb+GX8iwhPIFQt/ROVxLhWK/AvLVmBI6qDobF+3dU5rYVNFnshoUnMCHjQuHQGzkKKmLiPIFL340VItZVgdPNXqHscm+hR3BruHKQqe3Mk5a3I9Fmly1YXY4/tNHxG2DKuBs3EFYC/w5JCagiryQlrkO5LjmqYtGNs8Y1sa7ijuZP29Y83Cc8bm9h4UFt8X2FhWeHc43SoKYrC91jamC3miNVs/lwxYw=

matrix:
  include:
    - os: windows

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - python3-pip
            - python3-setuptools
        sonarcloud:
          organization: philips-software
          token:
            secure: "5AzPqoQ70TmiW4ZgTvmc3rUMd0E13dnYtIO4N00e+YCis624PhpdQDIfW4VotxZQtX6m/dYcj2CHgNUDgm7N4/t18jRVnFfv1+HqSoLBgdwIWIVhnX1kPdyQRxw/otaAhfRFjPcZCuJlJt0XRNTrBbEB/jyNm3Ad9kaa7lnw6WQWRisEgUI8veXNkFXO3WRKAW7xqZvK8Deojm8+CahtHtyqzTFoVtSoWQKWY83UfsicpRanYDtYW2znbJwjLqEoVLUksNXMzKtpjeXGiK5//VlVTFn7fmYuXAUMKphfAkvMEvTqFrR1Y+21swhnmNdAZKRwwrvh4BKU+eyZGuH6Sooc7bT+iuWeCEaJEVP87j9P9LoeGz/iD47qerXGEx7hNjK1BNKTkqT/agP420VtzbqfhKGoTk7BVB3XcqrQTARUGUDY5tsv+R+KHcMN8BMr2qeCpUKNgrolqTqXbnPRHkjjQAsQYAVcMgtOJem+AYQyZHrCBWYsu3Ybj6CdR4VvboNWtMi7UpQBn/H8eaFasQLHioSEHuuyv92MHA6iUQnlMJl5Vs73SWPY71g+OtahSWDEd3kdhox9bI3sLDeL+qifG7NWUW/B2ZKFvhbGMaxNEcwQWpOzG85MvuWKTS3fIozadJX+l4OtChG/sKsYxF+aBPmyW4oIky4ebvsXQ94="

      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - STATIC_ANALYSIS=1

    # - os: osx
    #   osx_image: xcode11
    #   env:
    #     - MACOSX_DEPLOYMENT_TARGET=10.15

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - if [[ $STATIC_ANALYSIS ]]; then pip3 install --user git+https://github.com/gcovr/gcovr.git; fi

script:
  - cmake -E make_directory Build
  - cd Build
  - if [[ $STATIC_ANALYSIS ]]; then cmake .. -DCCOLA_ENABLE_COVERAGE=ON -DCCOLA_DIR=ccola -DCCOLA_INSTALL_DIR=Install -DCMAKE_BUILD_TYPE=${BUILD_TYPE}; else cmake .. -DCCOLA_DIR=ccola -DCCOLA_INSTALL_DIR=Install -DCMAKE_BUILD_TYPE=${BUILD_TYPE}; fi
  - if [[ $STATIC_ANALYSIS ]]; then build-wrapper-linux-x86-64 --out-dir ../sonar-build-wrapper cmake --build . --config ${BUILD_TYPE}; else cmake --build . --config ${BUILD_TYPE}; fi
  - ctest -C ${BUILD_TYPE} -T Test --output-on-failure
  - if [[ $STATIC_ANALYSIS ]]; then gcovr --sonarqube=../coverage.xml -r ..; fi
  - if [[ $STATIC_ANALYSIS ]]; then cd .. && sonar-scanner; fi
