---
site:
  title: "EmIL: Embedded Infrastructure Library"
  url: https://philips-software.github.io/embeddedinfralib/
  start_page: embedded_infrastructure_library::index.adoc
content:
  branches: HEAD
  sources:
    - url: ./
      start_path: documents
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  attributes:
    :plantuml-server-url: http://www.plantuml.com/plantuml
  extensions:
    - asciidoctor-plantuml
